/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangjunjian_facerecognition_FaceRecognition */

#ifndef _Included_com_wangjunjian_facerecognition_FaceRecognition
#define _Included_com_wangjunjian_facerecognition_FaceRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangjunjian_facerecognition_FaceRecognition
 * Method:    detect
 * Signature: (Ljava/lang/String;Landroid/graphics/Rect;)V
 */
JNIEXPORT void JNICALL Java_com_wangjunjian_facerecognition_FaceRecognition_detect
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
